#!/bin/sh /etc/rc.common

# 执行顺序，通常 99 是最后启动
START=99
USE_PROCD=1

PROG_DIR="/etc/hnct-iptv"

start_service() {
    procd_open_instance
    
    # 1. 切换工作目录
    procd_set_param chdir "$PROG_DIR"
    
    # 2. 核心修正：显式设置 PYTHONPATH 环境变量
    # 确保 Python 能在 /etc/hnct-iptv 目录下找到 api_epg 模块
    procd_set_param env PYTHONPATH="$PROG_DIR"
    
    # 3. 执行命令
    procd_set_param command /usr/bin/python3 -u -m uvicorn api_epg:app \
		--host 0.0.0.0 \
		--port 1234 \
		--workers 1 \
		--loop uvloop \
		--http httptools \
		--log-level error
    
    # 自动重启设置
    procd_set_param respawn
    
    # 输出日志到 logread
    procd_set_param stderr 1
    procd_set_param stdout 1
    
    procd_close_instance
}

stop_service() {
    # procd 会自动根据 PID 处理停止，通常不需要额外写内容
    return 0
}
