#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service()
{
    procd_open_instance
    procd_set_param command \
        /usr/bin/python3 \
        -u \
        -m \
        uvicorn \
        api_epg:app \
        --host 0.0.0.0 \
        --port 1234 \
        --workers 1
    procd_set_param env PYTHONPATH="/etc/hnct-iptv/python_modules:/etc/hnct-iptv"
    procd_set_param chdir /etc/hnct-iptv
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    # procd 会自动根据 PID 处理停止，通常不需要额外写内容
    return 0
}
