#!/bin/sh

[ "$ACTION" = "ifup" ] || exit 0
[ "$INTERFACE" = "iptv" ] || exit 0

DEVICE=$(ubus call network.interface.iptv status | jsonfilter -e '@.l3_device')

[ -n "$DEVICE" ] || exit 0

TARGET_NETWORKS="
10.0.0.0/8
124.232.131.0/24
124.232.135.0/24
124.232.231.0/24
220.170.28.0/24
222.246.132.0/24
224.0.0.0/4
"

for NET in $TARGET_NETWORKS
do
    ip route del "$NET" dev "$DEVICE" 2>/dev/null
    
    ip route add "$NET" dev "$DEVICE"
    
    logger -t iptv-route "add static route $NET dev $DEVICE"
done

exit 0
