#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

PROG_DIR="/etc/hnct-iptv"

start_service()
{
    procd_open_instance

    procd_set_param chdir "$PROG_DIR"

    procd_set_param env \
        PYTHONPATH="/usr/lib/python3.11/site-packages:$PROG_DIR"

    procd_set_param command \
        /usr/bin/python3 \
        -u \
        -m \
        uvicorn \
        api_epg:app \
        --host 0.0.0.0 \
        --port 1234 \
        --workers 1 \
        --loop uvloop \
        --http httptools \
        --log-level error

    procd_set_param respawn

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {
    # procd 会自动根据 PID 处理停止，通常不需要额外写内容
    return 0
}
