name: build-rockchip-openwrt-24.10

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: '输入软路由型号，可选值如下：'
        options:
          - friendlyarm_nanopi-r2s
        required: true
        default: 'friendlyarm_nanopi-r2s'
      rootfs_partsize:
        description: '设置软件包大小，单位(MB)'
        required: true
        default: '1024'
      lan_ip:
        description: '设置 LAN IP 地址'
        required: true
        default: '192.168.4.1'
      enable_pppoe:
        description: '是否配置 PPPoE 拨号信息？'
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: '宽带账号 (若启用PPPoE)'
        required: false
      pppoe_password:
        description: '宽带密码 (若启用PPPoE)'
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
              
      - name: Free disk spece
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Set up OpenWRT build environment
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils python3-setuptools python3-pip python3-dev python3-pyelftools \
          rsync swig unzip zlib1g-dev file wget
      
      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi
      
      - name: Clone OpenWRT source code
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git fetch --tags
          LATEST_TAG=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          git checkout $LATEST_TAG
          echo "Using latest stable version: $LATEST_TAG"

      - name: Customize seeds
        run: |
          #cd openwrt
          # cat >> feeds.conf.default <<EOF
          # src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall.git;main
          # src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
          # EOF
          cd openwrt/package
          git clone https://github.com/xiaorouji/openwrt-passwall.git
          git clone https://github.com/xiaorouji/openwrt-passwall-packages.git
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          git clone https://github.com/jerrykuku/luci-app-argon-config.git
          git clone https://github.com/gdy666/luci-app-lucky.git lucky
      
      - name: Update and install the feeds
        run: |
          cd openwrt
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install libev libpam liblzma libnetsnmp curl \
          luci-lua-runtime luci-base csstidy luasrcdiet

      - name: Conform the feeds
        run: |
          cd openwrt
          ./scripts/feeds install -a

      - name: Modify Makefile for Rust 1.85
        run: |
          # 修改 Makefile 中的 Rust 版本号
          sed -i 's/PKG_VERSION:=1.84.0/PKG_VERSION:=1.85.0/' openwrt/feeds/packages/lang/rust/Makefile
          # 替换对应的 Rust 1.85 的 SHA256 哈希值
          sed -i 's/PKG_HASH:=15cee7395b07ffde022060455b3140366ec3a12cbbea8f1ef2ff371a9cca51bf/PKG_HASH:=2f4f3142ffb7c8402139cfa0796e24baaac8b9fd3f96b2deec3b94b4045c6a8a/' openwrt/feeds/packages/lang/rust/Makefile
          
      - name: Copy pre-existing .config file
        run: |
          cd openwrt
          cp ${{ github.workspace }}/rockchip/imm.config .config
          # yes | make oldconfig
      
      - name: Set LAN IP and PPPoE credentials
        run: |
          # 修改 network 配置文件中的 LAN IP
          cd openwrt
          sed -i 's/192.168.1.1/${{ github.event.inputs.lan_ip }}/g' package/base-files/files/bin/config_generate
          echo "lan_ip: ${{ github.event.inputs.lan_ip }}"
          # 配置 WAN 接口为 PPPoE，并添加用户名和密码
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            sed -i 's/"${2:-dhcp}"/"${2:-pppoe}"/g' package/base-files/files/lib/functions/uci-defaults.sh
            sed -i "s/username='username'/username='${{ github.event.inputs.pppoe_account }}'/g" package/base-files/files/bin/config_generate
            sed -i "s/password='password'/password='${{ github.event.inputs.pppoe_password }}'/g" package/base-files/files/bin/config_generate
            echo "pppoe_account: '${{ github.event.inputs.pppoe_account }}'"
            echo "pppoe_password: '${{ github.event.inputs.pppoe_password }}'"
          fi
      
      - name: Set root filesystem size
        run: |
          # 更新 CONFIG_TARGET_ROOTFS_PARTSIZE 配置
          cd openwrt
          sed -i "s/CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=${{ github.event.inputs.rootfs_partsize }}/g" .config
          echo "rootfs_partsize: ${{ github.event.inputs.rootfs_partsize }}"

      - name: Copy software config files
        run: |
          cd openwrt
          mkdir -p files/etc/config
          cp -r ${{ github.workspace }}/config/* files/etc/config/
      
      - name: Building Rockchip OpenWrt
        run: |
          cd openwrt
          make download -j$(nproc)
          make -j1 V=s
      
      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/openwrt/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
      
      - name: Upload OpenWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild
          name: OpenWrt-Rockchip
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/*.img.gz
            ${{ github.workspace }}/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
