name: build-rockchip-immortalwrt

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: '输入软路由型号，可选值如下：'
        options:
          - friendlyarm_nanopi-r2s
        required: true
        default: 'friendlyarm_nanopi-r2s'
      rootfs_partsize:
        description: '设置软件包大小，单位(MB)'
        required: true
        default: '1024'
      lan_ip:
        description: '设置 LAN IP 地址'
        required: true
        default: '192.168.4.1'
      enable_pppoe:
        description: '是否配置 PPPoE 拨号信息？'
        required: true
        default: 'yes'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: '宽带账号 (若启用PPPoE)'
        required: false
      pppoe_password:
        description: '宽带密码 (若启用PPPoE)'
        required: false
      enable_iptv:
        description: '是否添加 IPTV 接口 (适用湖南电信)'
        required: false
        default: 'yes'
        type: choice
        options:
        - 'yes'
        - 'no'
      iptv_pppoe_account:
        description: 'IPTV账号 (若启用IPTV)'
        required: false
      iptv_pppoe_password:
        description: 'IPTV密码 (若启用IPTV)'
        required: false
      enable_wireguard:
        description: '是否添加 WireGuard 接口'
        required: false
        default: 'yes'
        type: choice
        options:
        - 'yes'
        - 'no'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Free disk spece
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      
      - name: Set up ImmortalWrt build environment
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo apt-get autoclean
          sudo apt-get autoremove
      
      - name: Validate PPPoE、IPTV Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi
          
          if [[ "${{ inputs.enable_iptv }}" == "yes" ]]; then
            if [[ -z "${{ inputs.iptv_pppoe_account }}" || -z "${{ inputs.iptv_pppoe_password }}" ]]; then
              echo "Error: IPTV account and password must be provided when IPTV is enabled!"
              exit 1
            fi
          fi
      
      - name: Clone ImmortalWrt source code
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          git checkout openwrt-24.10
      
      - name: Customize seeds
        run: |
          cd immortalwrt
          git clone https://github.com/gdy666/luci-app-lucky.git package/lucky
      
      - name: Update and install the feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: Conform the feeds
        run: |
          cd immortalwrt
          ./scripts/feeds install -a
      
      # - name: Setup Rust version to 1.85.0
        # run: |
          # cd immortalwrt
          # 修改 Makefile 中的 Rust 版本号
          # sed -i 's/PKG_VERSION:=1.84.0/PKG_VERSION:=1.85.0/' feeds/packages/lang/rust/Makefile
          # 替换对应的 Rust 1.85 的 SHA256 哈希值
          # sed -i 's/PKG_HASH:=15cee7395b07ffde022060455b3140366ec3a12cbbea8f1ef2ff371a9cca51bf/PKG_HASH:=2f4f3142ffb7c8402139cfa0796e24baaac8b9fd3f96b2deec3b94b4045c6a8a/' feeds/packages/lang/rust/Makefile
      
      - name: Copy pre-existing .config file
        run: |
          cd immortalwrt
          cp ${{ github.workspace }}/imm/rockchip-r2s/imw.config .config
      
      - name: Set lan ip
        run: |
          # 设置 LAN IP
          cd immortalwrt
          cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-lan-ip
          uci -q batch <<-EOT >/dev/null 2>&1
          set network.lan.ipaddr='${{ inputs.lan_ip }}'
          set network.lan.dns='223.5.5.5'
          add_list network.lan.dns='119.29.29.29'
          commit network
          
          set network.@device[0].igmp_snooping='1'
          # set network.@device[0].query_interval='3000'
          commit network
          EOT
          
          /etc/init.d/network restart >/dev/null 2>&1
          exit 0
          EOF
          chmod +x package/base-files/files/etc/uci-defaults/99-set-lan-ip
      
      - name: Set pppoe
        run: |
          # 设置 PPPoE 用户名、密码以及 IPv6 设置
          cd immortalwrt
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-wan-pppoe
          uci -q batch <<-EOT >/dev/null 2>&1
          set network.wan.proto='pppoe'
          set network.wan.username='${{ inputs.pppoe_account }}'
          set network.wan.password='${{ inputs.pppoe_password }}'
          set network.wan.ipv6='auto'
          commit network
          
          delete network.wan6
          commit network
          
          set firewall.@zone[1].network='wan'
          commit firewall
          EOT
          
          /etc/init.d/network restart >/dev/null 2>&1
          /etc/init.d/firewall reload >/dev/null 2>&1
          exit 0
          EOF
            chmod +x package/base-files/files/etc/uci-defaults/99-set-wan-pppoe
          fi
      
      - name: Set iptv
        run: |
          # 设置 IPTV 用户名、密码
          cd immortalwrt
          if [[ "${{ inputs.enable_iptv }}" == "yes" ]]; then
            cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-iptv-interface
          uci -q batch <<-EOT >/dev/null 2>&1
          # 设置 IPTV 接口
          set network.iptv='interface'
          set network.iptv.device='eth2'
          set network.iptv.proto='pppoe'
          set network.iptv.username='${{ inputs.iptv_pppoe_account }}'
          set network.iptv.password='${{ inputs.iptv_pppoe_password }}'
          set network.iptv.defaultroute='0'
          commit network
          
          # 设置 IPTV 防火墙
          set firewall.iptv='zone'
          set firewall.iptv.name='iptv'
          set firewall.iptv.network='iptv'
          set firewall.iptv.input='ACCEPT'
          set firewall.iptv.output='ACCEPT'
          set firewall.iptv.forward='ACCEPT'
          set firewall.iptv.masq='1'
          set firewall.iptv.mtu_fix='1'
          add firewall forwarding
          set firewall.@forwarding[-1].src='lan'
          set firewall.@forwarding[-1].dest='iptv'
          commit firewall
          
          # 添加 IPTV 静态路由
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='10.0.0.0/8'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='61.150.160.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='124.232.131.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='124.232.135.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='124.232.149.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='124.232.231.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='175.10.54.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='220.168.138.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='220.170.28.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='222.246.132.0/24'
          add network route
          set network.@route[-1].interface='iptv'
          set network.@route[-1].target='239.76.0.0/16'
          commit network
          EOT
          
          /etc/init.d/network restart >/dev/null 2>&1
          /etc/init.d/firewall reload >/dev/null 2>&1
          exit 0
          EOF
            chmod +x package/base-files/files/etc/uci-defaults/99-set-iptv-interface
          fi
      
      - name: Set wireguard
        run: |
          # 添加 wireguard 接口
          cd immortalwrt
          if [[ "${{ inputs.enable_wireguard }}" == "yes" ]]; then
            cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-wireguard-interface
          uci -q batch <<-EOT >/dev/null 2>&1
          # 创建 wireguard 接口
          set network.wg='interface'
          set network.wg.proto='wireguard'
          set network.wg.private_key='${{ secrets.WG_HNCT_PRIVATE_KEY }}'
          set network.wg.addresses='192.168.3.3'
          commit network
          
          # 配置 wireguard 设置
          add network wireguard_wg
          set network.@wireguard_wg[-1].description='OpenWrt_CT'
          set network.@wireguard_wg[-1].public_key='${{ secrets.WG_SHCU_PUBLIC_KEY }}'
          set network.@wireguard_wg[-1].private_key='${{ secrets.WG_SHCU_PRIVATE_KEY }}'
          set network.@wireguard_wg[-1].preshared_key='${{ secrets.WG_HNCT_PRESHARED_KEY }}'
          add_list network.@wireguard_wg[-1].allowed_ips='192.168.2.0/24'
          add_list network.@wireguard_wg[-1].allowed_ips='192.168.3.0/24'
          add_list network.@wireguard_wg[-1].allowed_ips='192.168.5.0/24'
          set network.@wireguard_wg[-1].route_allowed_ips='1'
          set network.@wireguard_wg[-1].endpoint_host='${{ secrets.WG_ENDPOINT_HOST }}'
          set network.@wireguard_wg[-1].endpoint_port='${{ secrets.WG_ENDPOINT_PORT }}'
          set network.@wireguard_wg[-1].persistent_keepalive='25'
          commit network
          
          # 配置防火墙
          add_list firewall.@zone[0].network='wg'
          commit firewall
          EOT
          
          /etc/init.d/network restart >/dev/null 2>&1
          /etc/init.d/firewall reload >/dev/null 2>&1
          exit 0
          EOF
            chmod +x package/base-files/files/etc/uci-defaults/99-set-wireguard-interface
          fi
      
      - name: Add firewall rules
        run: |
          cd immortalwrt
          cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-firewall
          uci -q batch <<-EOT >/dev/null 2>&1
          # 添加 Allow-UDP-IGMPProxy 规则
          add firewall rule
          set firewall.@rule[-1].name='Allow-UDP-IGMPProxy'
          add_list firewall.@rule[-1].proto='udp'
          set firewall.@rule[-1].src='wan'
          set firewall.@rule[-1].dest='lan'
          set firewall.@rule[-1].dest_ip='224.0.0.0/4'
          set firewall.@rule[-1].family='ipv4'
          set firewall.@rule[-1].target='ACCEPT'

          # 添加 Allow-UDP-Udpxy 规则
          add firewall rule
          set firewall.@rule[-1].name='Allow-UDP-Udpxy'
          add_list firewall.@rule[-1].proto='udp'
          set firewall.@rule[-1].src='wan'
          set firewall.@rule[-1].dest_ip='224.0.0.0/4'
          set firewall.@rule[-1].target='ACCEPT'
          
          # 添加 Web-Proxy-HTTPS 规则
          add firewall rule
          set firewall.@rule[-1].name='Web-Proxy-HTTPS'
          add_list firewall.@rule[-1].proto='tcp'
          set firewall.@rule[-1].src='wan'
          set firewall.@rule[-1].dest_port='8443'
          set firewall.@rule[-1].target='ACCEPT'

          # 添加 Web-Proxy-HTTP 规则
          add firewall rule
          set firewall.@rule[-1].name='Web-Proxy-HTTP'
          add_list firewall.@rule[-1].proto='tcp'
          set firewall.@rule[-1].src='wan'
          set firewall.@rule[-1].dest_port='8444'
          set firewall.@rule[-1].target='ACCEPT'
          
          # 添加 Lucky 规则
          add firewall rule
          set firewall.@rule[-1].name='Lucky'
          add_list firewall.@rule[-1].proto='tcp'
          set firewall.@rule[-1].src='wan'
          set firewall.@rule[-1].dest_port='16601'
          set firewall.@rule[-1].target='ACCEPT'
          commit firewall
          EOT
          
          /etc/init.d/firewall reload >/dev/null 2>&1
          exit 0
          EOF
          chmod +x package/base-files/files/etc/uci-defaults/99-set-firewall

      - name: Set dhcp
        run: |
          cd immortalwrt
          cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-dhcp
          uci -q batch <<-EOT >/dev/null 2>&1
          delete dhcp.@dnsmasq[0].dns_redirect
          set dhcp.lan.dhcpv6='server'
          set dhcp.lan.ra='server'
          commit dhcp
          EOT
          
          /etc/init.d/odhcpd restart >/dev/null 2>&1
          exit 0
          EOF
          chmod +x package/base-files/files/etc/uci-defaults/99-set-dhcp

      - name: Set system
        run: |
          cd immortalwrt
          cat <<EOF > package/base-files/files/etc/uci-defaults/99-set-system
          uci -q batch <<-EOT >/dev/null 2>&1
          set system.@system[0].conloglevel='1'
          set system.@system[0].cronloglevel='9'
          commit system
          EOT
          
          /etc/init.d/log restart >/dev/null 2>&1
          /etc/init.d/cron restart >/dev/null 2>&1
          /etc/init.d/system restart >/dev/null 2>&1
          exit 0
          EOF
          chmod +x package/base-files/files/etc/uci-defaults/99-set-system
      
      # - name: Set install flask_cors
        # run: |
          # cd immortalwrt
          # cat <<EOF > package/base-files/files/etc/uci-defaults/99-install-flask-cors
          # pip install flask_cors
          # exit 0
          # EOF
          # chmod +x package/base-files/files/etc/uci-defaults/99-install-flask-cors
      
      # - name: Set LAN IP and PPPoE credentials
        # run: |
          # 修改 network 配置文件中的 LAN IP
          # cd immortalwrt
          # sed -i 's/192.168.1.1/${{ inputs.lan_ip }}/g' package/base-files/files/bin/config_generate
          # echo "lan_ip: ${{ inputs.lan_ip }}"
          # 配置 WAN 接口为 PPPoE，并添加用户名和密码
          # if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            # sed -i 's/"${2:-dhcp}"/"${2:-pppoe}"/g' package/base-files/files/lib/functions/uci-defaults.sh
            # sed -i "s/username='username'/username='${{ inputs.pppoe_account }}'/g" package/base-files/files/bin/config_generate
            # sed -i "s/password='password'/password='${{ inputs.pppoe_password }}'/g" package/base-files/files/bin/config_generate
            # echo "pppoe_account: '${{ inputs.pppoe_account }}'"
            # echo "pppoe_password: '${{ inputs.pppoe_password }}'"
          # fi
      
      - name: Set root filesystem size
        run: |
          # 更新 CONFIG_TARGET_ROOTFS_PARTSIZE 配置
          cd immortalwrt
          sed -i "/CONFIG_TARGET_ROOTFS_PARTSIZE/d" .config
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=${{ inputs.rootfs_partsize }}" >> .config
          echo "rootfs_partsize: ${{ inputs.rootfs_partsize }}"
      
      - name: Copy software config files
        run: |
          cd immortalwrt
          mkdir -p files/etc
          # mkdir -p files/etc/crontabs
          # mkdir -p files/www
          
          if [[ "${{ inputs.profile }}" == "friendlyarm_nanopi-r2s" ]]; then
            # cp -r ${{ github.workspace }}/crontabs/* files/etc/crontabs/
            cp -r ${{ github.workspace }}/conf/rockchip-r2s/etc/* files/etc/
            # cp -r ${{ github.workspace }}/www/* files/www/
          fi
      
      - name: Building Rockchip ImmortalWrt
        run: |
          cd immortalwrt
          make
      
      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/immortalwrt/bin/targets/rockchip/armv8/*.img.gz ${{ github.workspace }}
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
      
      - name: Upload ImmortalWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: rockchip
          name: ImmortalWrt-Rockchip
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/*.img.gz
            ${{ github.workspace }}/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
